# Generated by Django 3.2.25 on 2024-07-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback')], default='PB', max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
