# Generated by Django 3.2.25 on 2024-07-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20240702_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('HB', 'Hardback'), ('PB', 'Paperback')], default='PB', max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
